name: Deploy to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_VERSION: "18" # Default Node.js version

jobs:
  build:
    runs-on: ubuntu-latest

    # Optionally, test multiple Node.js versions
    strategy:
      matrix:
        node-version: ["18", "20"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Project
        run: |
          yarn run build
          mkdir -p ./out/multichain
          mv multichain/blocklist-full.json ./out/multichain/
          mv blocklist-full.json ./out/



